version: '3.7'
services:
  jabberwocky:
    build:
      context: .
      dockerfile: Dockerfile
    image: jabberwocky
    container_name: jabberwocky-container
    volumes:
      - ~/.openai:/.openai
      - ${DATA_PATH}:/gui/data
      - ${BIN_PATH}:/gui/bin
