version: '3.7'
services:
  jabberwocky:
    build:
      context: .
      dockerfile: Dockerfile
    image: jabberwocky
    container_name: jabberwocky-container
    volumes:
      - ~/.openai:/.openai
      - ../data:data
      - ../bin:bin
