PROMPTS_PATH=$(cd ../data/prompts && pwd)
PERSONAS_PATH=$(cd ../data/conversation_personas && pwd)
CUSTOM_PERSONAS_PATH=$(cd ../data/conversation_personas_custom && pwd)
CONVERSATIONS_PATH=$(cd ../data/conversations && pwd)
COMPLETIONS_PATH=$(cd ../data/completions && pwd)
LOGS_PATH=$(cd ../data/logs && pwd)
FONTS_PATH=$(cd ../data/fonts && pwd)
BIN_PATH=$(cd ../bin && pwd)
